export const TemplateRoles = [
  {
    id: 1,
    name: "990",
    description: "990 preparation",
    invoice: "990 preparation",
    officeaddress: "HQ",
    Category: "CORPTAX",
    biller: "",
    Review: "",
    Manager: "",
    status: 1,
  },
  {
    id: 2,
    name: "1099",
    description: "Form 1099 Preparation",
    invoice: "Form 1099 Preparation",
    officeaddress: "HQ",
    Category: "TAX",
    biller: "",
    Review: "",
    Manager: "",
    status: 0,
  },
  {
    id: 3,
    name: "10Q",
    description: "Form10Q preparation",
    invoice: "Form10Q preparation",
    officeaddress: "HQ",
    Category: "CONSULT",
    biller: "ISOGAWA HIRO",
    Review: "ISOGAWA HIRO",
    Manager: "ISOGAWA HIRO",
    status: 1,
  },
];
